# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7218b21426dac0048edb2d6a87076280098c029bbb4a7f5a01a1537f4bc36a278303cf8d61f7c64df34377d82322ac674f02cc2c7c5f59aa4e2d6a3261e750ca

test:
  secret_key_base: 457b4a5d1a3b873e3c96142e9cdb6d6be4e43f68c9872c94bf6b3184eee86a00f38b6191dc814724cdebe6ee35ed7accb2989d9241a54f34cb05d9f41496f7da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
